linters-settings:
  golint:
    min-confidence: 0.2
  goimports:
    local-prefixes: github.com/sidletsky/sitemap
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  enable:
    - gofmt
    - govet
    - gocritic
    - megacheck
